<?php

namespace Database\Seeders;

use App\Models\UseCase;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UseCaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('use_case_categories')->insert([
            ['name' => 'Professional Services', 'slug' => 'professional-services', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Blog', 'slug' => 'blog', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Email', 'slug' => 'email', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Social Media', 'slug' => 'social-media', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Content', 'slug' => 'content', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'slug' => 'other', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Website', 'slug' => 'website', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Video', 'slug' => 'video', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Educational', 'slug' => 'educational', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tools', 'slug' => 'tools', 'is_published' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::statement("INSERT INTO `use_cases` (`id`, `title`, `icon`, `details`, `prompt`, `use_case_category_id`, `is_popular`, `title_label`, `short_description_label`, `description_label`, `title_placeholder`, `short_description_placeholder`, `description_placeholder`, `type`, `is_published`, `created_at`, `updated_at`) VALUES
                (2, 'Blog Conclusion', 'assets/uploads/useCase/2023/04/11/blog-conclusion8563.png', 'Your blog content should conclude with a captivating paragraph.', 'I\'m writing a blog on [title]. In short The blog is about[description]. Suggest me a conlcusion for this blog?', 2, 1, 'Blog Title', '', 'Blog Description', 'Write your blog title here', 'Write short description here', 'Describe your blog post', 2, 1, '2023-04-08 10:08:06', '2023-04-17 20:48:36'),
                (3, 'Blog Intros', 'assets/uploads/useCase/2023/04/11/blog-intros9398.png', 'Create an introduction that will encourage readers to continue to reads your content.', 'I\'m writing a blog on [title]. In short The blog is about[description]. Suggest me the intro for this blog?', 2, 1, 'Blog Title', '', 'Blog Description', 'Write your blog title here', 'Write short description here', 'Describe your blog post', 1, 1, '2023-04-08 10:33:25', '2023-04-17 20:47:12'),
                (4, 'Blog Ideas', 'assets/uploads/useCase/2023/04/11/blog-ideas5487.png', 'The ideal instrument for beginning to write excellent articles. Develop unique thoughts for your upcoming post.', 'I want to write a blog on [title]. Give me 3 ideas on how can I write the blog with outlines.', 2, 1, 'Description', '', '', 'Describe your blog post', 'Write short description here', 'Write description here', 1, 1, '2023-04-08 12:04:12', '2023-04-17 20:46:19'),
                (5, 'Blog Section', 'assets/uploads/useCase/2023/04/11/blog-section8294.png', 'Describe in detail a subheading from your article in a blog section (a few paragraphs).', 'Write me a blog which title is [title] and the blog subheadings are [short_description]', 2, 1, 'Blog Title', 'Sub Headings', '', 'Write your blog title here', 'Technology, Artificial intelligence', 'Write description here', 1, 1, '2023-04-08 12:13:58', '2023-04-17 20:44:49'),
                (6, 'Blog Titles', 'assets/uploads/useCase/2023/04/11/blog-titles3143.png', 'Compose a complete blog piece (a few paragraphs) about one of your article\'s subheadings.', 'Write me 5 blog titles about [title]', 2, 1, 'Keywords', '', '', 'Technology, Artificial intelligence', 'Write short description here', 'Write description here', 1, 1, '2023-04-09 04:18:46', '2023-04-17 20:45:26'),
                (7, 'Facebook Ads', 'assets/uploads/useCase/2023/04/11/facebook-ads2159.png', 'Creating Facebook ads using your target market in mind will increase your conversion rate.', 'Give me Facebook Ads ideas for my product[title] The product is [short_description]', 4, 1, 'Input product name', 'Inputs products short description', '', 'Input product name', 'nputs products short description', 'Write description here', 1, 1, '2023-04-11 15:48:54', '2023-04-17 20:49:33'),
                (8, 'Article Generator', 'assets/uploads/useCase/2023/04/11/article-generator1535.png', 'Write an article of the best quality using a title and an outline in a short amount of time.', 'Write me an Article that includes the given keywords [short_description]. The title of the Article is \"[title]\", and here\'s a little bit about the article, [description].', 5, 1, 'Article Title', 'Given keywords', 'Description', 'Write your article title here', 'Technology, Artificial intelligence, Machine Learning', 'escribe your article', 1, 1, '2023-04-11 15:55:53', '2023-04-17 20:50:30'),
                (9, 'Content Rewriter', 'assets/uploads/useCase/2023/04/11/content-rewriter3696.png', 'Rewrite a piece of material to make it more intriguing, original, and compelling.', '[description] Rewrite this content to make it more intriguing, original, and compelling.', 5, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Enter your content to rewrite', 1, 1, '2023-04-11 16:02:46', '2023-04-17 20:51:10'),
                (10, 'Paragraph Generator', 'assets/uploads/useCase/2023/04/11/paragraph-generator4672.png', 'Create sentences on any subject, with a keyword, and in a certain voice.', 'Write me a Paragraph that includes the given keywords [short_description]. The title of the Paragraph is \"[title]\",', 6, 1, 'Title of the Paragraph', 'Given keywords', '', 'Write your Paragraph title here', 'Technology, Artificial intelligence, Machine Learning', 'Write description here', 1, 1, '2023-04-11 16:05:28', '2023-04-17 20:52:27'),
                (11, 'Talking Points', 'assets/uploads/useCase/2023/04/11/talking-points3467.png', 'For your article\'s subheadings, create bullet points that are brief, clear, and instructive.', '\"Provide me with Talking Points that include the given keywords [short_description]. The title of the Talking Points\r\nshould be \"\"[title]\"\", and the description should be \"\"[description]\"\".', 6, 1, 'Title', 'Keywords', 'Description', 'Write your title here', 'Technology, Artificial intelligence, Machine Learning', 'Describe your talking points', 1, 1, '2023-04-11 16:06:40', '2023-04-17 20:53:58'),
                (12, 'Pros & Cons for blogs', 'assets/uploads/useCase/2023/04/11/pros-cons-for-blogs2323.png', 'For your blog piece, list the pros and cons of a service, goods, or website.', 'Write me the pros and cons of [title]', 2, 1, 'Title', '', '', 'Write your title here', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:08:04', '2023-04-17 20:54:59'),
                (13, 'Summarize Text', 'assets/uploads/useCase/2023/04/11/summarize-text2947.png', 'Summarize any text in a clear, succinct, and understandable manner.', 'Summarize this paragraph [title].', 6, 1, 'Description', '', '', 'Enter your text to summarize', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:09:18', '2023-04-17 20:57:34'),
                (14, 'Product Description', 'assets/uploads/useCase/2023/04/11/product-description1481.png', 'Create a description of your product that explains its value.', 'Write me a product description for [title]. The category of the product is [short_description]. The description of the product is [description]', 5, 1, 'Title', 'Category of the product', 'Keywords', 'Write your title here', 'Write your product category', 'Describe your products briefly', 1, 1, '2023-04-11 16:11:36', '2023-04-17 20:58:32'),
                (15, 'Startup Name Generator', 'assets/uploads/useCase/2023/04/11/startup-name-generator3465.png', 'Create interesting, original, and memorable names for your startup in a matter of seconds.', 'Generate some cool, creative, and catchy names for a startup business. The type/sector of business is [description]. Give me the response in [description] language.', 5, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Explain what your startup idea is about', 1, 1, '2023-04-11 16:13:01', '2023-04-17 20:59:18'),
                (16, 'Product Name Generator', 'assets/uploads/useCase/2023/04/11/product-name-generator566.png', 'Using illustrative words, come up with inventive product names', 'Create creative product names that include the given keywords [title]. The description of the product is  \" [description]\".', 5, 1, 'Keywords', '', 'Product Description', 'Mobile phone, Android, Flagship', 'Write short description here', 'Describe your product', 1, 1, '2023-04-11 16:16:11', '2023-04-17 21:00:13'),
                (17, 'SEO Meta Description', 'assets/uploads/useCase/2023/04/11/seo-meta-description2754.png', 'Based on the description, create a meta description that is SEO-friendly.', 'Provide me with SEO-friendly Meta Description for my product/service named [title]The description of my product/service is  [description]', 7, 1, 'Product/Service Name', '', 'Description', 'Name of your product/service', 'Write short description here', 'Describe your product/service', 1, 1, '2023-04-11 16:19:26', '2023-04-17 21:01:00'),
                (18, 'FAQs', 'assets/uploads/useCase/2023/04/11/faqs6625.png', 'Create commonly asked questions based on the description of your product.', 'Generate some Frequently asked questions for [title]. Here\'s some brief about the FAQ: [description]', 7, 1, 'Title', '', 'Description', 'Product/service Name', 'Write short description here', 'Describe briefly about your Product/service', 1, 1, '2023-04-11 16:20:35', '2023-04-17 21:01:50'),
                (19, 'FAQ Answers', 'assets/uploads/useCase/2023/04/11/faq-answers4103.png', 'Generate creative answers to questions (FAQs) about your business or website.', 'Generate some Frequently asked questions and answers for [title]. Here\'s some brief about the FAQ:[description]', 7, 1, 'Title', '', 'Description', 'Product/service Name', 'Write short description here', 'What is the question you are generationg answers for', 1, 1, '2023-04-11 16:22:18', '2023-04-17 21:03:59'),
                (20, 'Testimonials/Reviews', 'assets/uploads/useCase/2023/04/11/testimonialsreviews4719.png', 'User testimonials will give your website social evidence.', 'Write a testimonial/review for a product named [title]. The description of the product is [description]', 7, 1, 'Product Name', '', 'Description', 'Product/service Name', 'Write short description here', 'Describe briefly about the Product/service', 1, 1, '2023-04-11 16:23:24', '2023-04-17 21:04:45'),
                (21, 'YouTube Video Descriptions', 'assets/uploads/useCase/2023/04/11/youtube-video-descriptions8377.png', 'Catchy and persuasive YouTube descriptions that help your videos rank higher.', '\"Write me a Video Description for my youtube video titled as\r\n[title], and the video is about[description]', 8, 1, 'Title', '', 'Description', 'Write your video title', 'Write short description here', 'Briefly describe what the video is about', 1, 1, '2023-04-11 16:25:30', '2023-04-17 21:05:21'),
                (22, 'Video Titles', 'assets/uploads/useCase/2023/04/11/video-titles5742.png', 'To get everyone\'s attention, create a catchy title for your video.', 'Write me some catchy Video title for my video. The video is about [title]', 8, 1, 'Description', '', '', 'Briefly describe what the video is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:26:20', '2023-04-17 21:06:03'),
                (23, 'Youtube Tags Generator', 'assets/uploads/useCase/2023/04/11/youtube-tags-generator3861.png', 'Create YouTube tags and phrases that are ideal for SEO.', 'Generate Youtube Tag for a video named [title] The video is about [description][Description]\".', 8, 1, 'Title', NULL, 'Description', 'Write here', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:27:03', '2023-04-11 16:27:03'),
                (24, 'Youtube Caption', 'assets/uploads/useCase/2023/04/11/youtube-captionstitles5787.png', 'Create engaging YouTube captions to get viewers to your video.', 'Write me some Video caption for a Youtube video. The video is about [title]', 8, 1, 'Title', '', 'Description', 'Write your video title', 'Write short description here', 'Briefly describe what the video is about', 1, 1, '2023-04-11 16:27:55', '2023-04-17 21:07:46'),
                (25, 'Youtube Hashtag Generator', 'assets/uploads/useCase/2023/04/11/youtube-hashtag-generator4367.png', 'Create YouTube tags and phrases that are ideal for SEO.', 'Generate Youtube Hashtags for a video named [title] The video is about [description]', 8, 1, 'Title', '', 'Description', 'Write your video title', 'Write short description here', 'Briefly describe what the video is about', 1, 1, '2023-04-11 16:28:36', '2023-04-17 21:08:27'),
                (26, 'Instagram Captions', 'assets/uploads/useCase/2023/04/11/instagram-captions4684.png', 'Create engaging Instagram Captions to get viewers to your video.', 'Generate an attracting Instagram caption for a post about [description]', 4, 1, '', '', 'Description', 'Write Description Here', 'Write short description here', 'Briefly describe what the post is about', 1, 1, '2023-04-11 16:29:43', '2023-05-04 19:09:26'),
                (27, 'Instagram Hashtags Generator', 'assets/uploads/useCase/2023/04/11/instagram-hashtags-generator5549.png', 'Create Instagram tags and phrases that are ideal for SEO.', 'Generate some Instagram hashtags for a post about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:30:20', '2023-04-17 21:10:41'),
                (28, 'Social Media Post (Personal)', 'assets/uploads/useCase/2023/04/11/social-media-post-personal3044.png', 'Create a personal social media post that will appear on any platform.', 'Generate some Social Media Post for my personal account. The post is about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:31:05', '2023-04-17 21:11:09'),
                (29, 'Social Media Post (Business)', 'assets/uploads/useCase/2023/04/11/social-media-post-business1153.png', 'Create a business social media post that will appear on any platform.', 'Generate some Social Media Post for my Business named [title] The post is about [description] Here is additional information about the Company[short_description]', 4, 1, 'Business Name', 'Keywords', 'Description', 'Write your business name here', 'Briefly describe what the post is about', 'Mobile phone, Android, Flagship', 1, 1, '2023-04-11 16:33:33', '2023-04-17 21:11:53'),
                (30, 'Facebook Ads Headlines', 'assets/uploads/useCase/2023/04/11/facebook-ads-headlines4450.png', 'To make your Facebook ads stand out, create intriguing and persuasive headlines.', 'Provide me with few Facebook Ads headline for my product/service named [title]  The description of my product/service is [description]', 4, 1, 'Title', '', 'Description', 'Write your product/service name', 'Write short description here', 'Briefly describe about your product/service', 1, 1, '2023-04-11 16:34:39', '2023-04-17 21:12:30'),
                (31, 'Facebook Caption Generator', 'assets/uploads/useCase/2023/04/11/facebook-caption-generator5633.png', 'Create engaging Facebook Captions to get viewers to your video.', 'Write me few caption for a Facebook post. The post is about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:36:39', '2023-04-17 21:13:01'),
                (32, 'Facebook Hashtag Generator', 'assets/uploads/useCase/2023/04/11/facebook-hashtag-generator5311.png', 'Create Facebook tags and phrases that are ideal for SEO.', 'Generate some Hashtags for a Facebook post. The Post is about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:37:29', '2023-04-17 21:13:35'),
                (33, 'Google Ads Headlines', 'assets/uploads/useCase/2023/04/11/google-ads-headlines8890.png', 'Create intriguing 30-character headlines to use in Google AdWords to market your goods.', 'Provide me few Google Ads headline for my product/service named [title]. The description of my product/service is [description].', 4, 1, 'Title', '', 'Description', 'Write your product/service name', 'Write short description here', 'Briefly describe about your product/service', 1, 1, '2023-04-11 16:38:36', '2023-04-17 21:14:14'),
                (34, 'Google Ads Description', 'assets/uploads/useCase/2023/04/11/google-ads-description1592.png', 'Create a Google AdWords description that distinguishes your ad and produces leads.', 'Provide me some Google Ads description for my product/service named [title]. The keywords for the Ad are [short_description]', 4, 1, 'Keywords', 'Short Description', '', 'Write your product/service name', 'Mobile phone, Android, Flagship', 'Write description here', 1, 1, '2023-04-11 16:39:20', '2023-04-17 21:18:06'),
                (35, 'Academic Essay', 'assets/uploads/useCase/2023/04/11/academic-essay4524.png', 'Write original academic essays for a variety of subjects in a flash.', '\"Write an academic essay on the [title] topic\r\nThe keywords for the essay are [short_description]', 5, 1, 'Essay Title', 'Short Description', '', 'Write your essay title here', 'Mobile phone, Android, Flagship', 'Write description here', 1, 1, '2023-04-11 16:40:54', '2023-04-17 21:18:41'),
                (36, 'Welcome Email', 'assets/uploads/useCase/2023/04/11/welcome-email1286.png', 'Send out welcome emails to your clients.', 'Generate an Welcome email for my client named [title]. My client\'s position Must include these details [description]', 3, 1, 'Recipient Name', '', 'Description', 'Write the name of the person receiving the Email', 'Write short description here', 'Briefly describe what the email is about', 1, 1, '2023-04-11 16:41:59', '2023-04-17 21:19:17'),
                (37, 'Email', 'assets/uploads/useCase/2023/04/11/email7333.png', 'Make effective emails with the help of AI.', 'Generate an email for my client named [title] with a beautiful subject. The email is about [description][Description].', 3, 1, 'Recipient Name', '', 'Description', 'Write the name of the person receiving the Email', 'Write short description here', 'Briefly describe what the email is about', 1, 1, '2023-04-11 16:42:41', '2023-04-17 21:20:01'),
                (38, 'Email Subject Lines', 'assets/uploads/useCase/2023/04/11/email-subject-lines561.png', 'With a few clicks, create professional email subject lines', 'Generate 10 email subject lines for my product/service named [title]. Must include these details [description]', 3, 1, 'Product/service name', '', 'Description', 'Write your product/service name', 'Write short description here', 'Briefly describe about your product/service', 3, 1, '2023-04-11 16:43:24', '2023-10-20 16:42:57'),
                (39, 'Creative Stories', 'assets/uploads/useCase/2023/04/11/creative-stories6453.png', 'Give AI the freedom to create stories for you based on text you provide.', '\"Provide me with Creative Stories that include the given keywords [keywords]. The title of the Creative Stories\r\nshould be [title], and the description should be [description]', 5, 1, 'Title', 'Keywords', 'Description', 'Title of your story', 'Mobile phone, Android, Flagship', 'Briefly describe about your story', 3, 1, '2023-04-11 16:44:39', '2023-10-20 16:45:26'),
                (40, 'Grammar Checker', 'assets/uploads/useCase/2023/04/11/grammar-checker591.png', 'Make sure your content is free of mistakes.', 'Check the grammar for the following paragraph: [description]. Also mark the mistakes.', 5, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Write tour content here', 1, 1, '2023-04-11 16:45:40', '2023-04-17 21:22:06'),
                (41, 'Summarize for 2nd Grader', 'assets/uploads/useCase/2023/04/11/summarize-for-2nd-grader3267.png', 'Summarize any difficult material for a child in 2nd grade.', 'Summarize this following content for 2nd grader child :[description]', 5, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Write tour content here', 1, 1, '2023-04-11 16:46:35', '2023-04-17 21:22:41'),
                (42, 'Video Scripts', 'assets/uploads/useCase/2023/04/11/video-scripts8200.png', 'Make your video scripts as soon as possible, then begin filming.', 'write me a Video Script for a video [title].', 8, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Briefly describe what the story is about', 1, 1, '2023-04-11 16:47:18', '2023-04-17 21:23:10'),
                (43, 'Amazon Product Description', 'assets/uploads/useCase/2023/04/11/amazon-product-description7525.png', 'Construct a compelling Amazon product description.', 'Write me an Amazon product description for my product/service named[title]. The keywords for the ad are [short_description]', 6, 1, 'Product/Service Name', 'Short Description', '', 'Write your product/service name', 'Briefly describe about your product/service', 'Write description here', 1, 1, '2023-04-11 16:48:55', '2023-04-17 21:24:16'),
                (44, 'Linkedln Caption Generator', 'assets/uploads/useCase/2023/04/11/linkedln-caption-generator6433.png', 'Design and build a powerful Linkedln Caption Generator', 'Write me few captions for my LinkedIn post. The post is about[title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:50:06', '2023-04-17 21:24:45'),
                (45, 'Linkedln Hashtag Generator', 'assets/uploads/useCase/2023/04/11/linkedln-hashtag-generator2815.png', 'Design and build a powerful LinkedIn Hashtag Generator', 'Generate Hashtags for my LinkedIn post. The Post is about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 3, 1, '2023-04-11 16:50:53', '2023-10-20 16:41:02'),
                (46, 'Twitter Caption', 'assets/uploads/useCase/2023/04/11/twitter-caption3523.png', 'Create engaging Twitter captions to get viewers to your video.', 'Generate a Twitter caption for my tweet about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:53:28', '2023-04-17 21:25:40'),
                (47, 'Twitter Hashtag', 'assets/uploads/useCase/2023/04/11/twitter-hashtag689.png', 'Create Twitter tags and phrases that are ideal for SEO.', 'Generate some Twitter hashtags for my tweet about [title].', 4, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Briefly describe what the post is about', 1, 1, '2023-04-11 16:55:11', '2023-04-17 21:26:47'),
                (48, 'TikTok Caption', 'assets/uploads/useCase/2023/04/11/tiktok-caption7995.png', 'Create engaging TikTok captions to get viewers to your video.', 'Generate a TikTok caption for a post about [title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:56:10', '2023-04-17 21:27:15'),
                (49, 'Tiktok Hashtag Generator', 'assets/uploads/useCase/2023/04/11/tiktok-hashtag-generator3541.png', 'Create TikTok Hashtag Generator and phrases that are ideal for SEO.', 'Generate Hashtag for my Tiktok post. The Tiktok is about[title]', 4, 1, 'Description', '', '', 'Briefly describe what the post is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 16:56:52', '2023-04-17 21:27:41'),
                (50, 'Email Body Generator', 'assets/uploads/useCase/2023/04/11/email-body-generator7235.png', 'To attract viewers to your email, create interesting email body generator.', 'Generate an email body for the email named [title]. Must include these details [description]', 3, 1, 'Subject', '', 'Description', 'Write your email subject here', 'Write short description here', 'Briefly describe what the email is about', 1, 1, '2023-04-11 16:57:34', '2023-04-17 21:28:10'),
                (51, 'Web Content Generator', 'assets/uploads/useCase/2023/04/11/web-content-generator8024.png', 'Create interesting Web Content Generator to draw readers to your email.', 'Generate the Web Content named [title], The description of the content is  [description]', 5, 1, 'Title', '', 'Description', 'Write your title here', 'Write short description here', 'Briefly describe what the content is about', 1, 1, '2023-04-11 16:58:25', '2023-04-17 21:28:46'),
                (52, 'Blog Meta Description', 'assets/uploads/useCase/2023/04/11/blog-meta-description6399.png', 'Create your blog\'s meta description.', 'Generate a blog meta description for my blog [description]', 2, 1, '', '', 'Description', 'Write here', 'Write short description here', 'Briefly describe what the blog is about', 1, 1, '2023-04-11 16:59:46', '2023-04-17 21:29:11'),
                (53, 'Blog Tag Generator', 'assets/uploads/useCase/2023/04/11/blog-tag-generator1398.png', 'Create Blog tags Generator that are ideal for SEO.', 'Generate some blog tags for my blog post about [title]', 2, 1, 'Description', '', '', 'Briefly describe what the blog is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 17:00:22', '2023-04-17 21:29:36'),
                (54, 'Blog ALT Text Generator', 'assets/uploads/useCase/2023/04/11/blog-alt-text-generator7454.png', 'Create Blog Alt Tags Generators that are ideal for SEO.', 'Generate my blog  Image ALT Text for an image about [title]', 2, 1, 'Description', '', '', 'Briefly describe what the blog is about', 'Write short description here', 'Write description here', 1, 1, '2023-04-11 17:00:57', '2023-04-17 21:30:02'),
                (56, 'Letter Writing', 'assets/uploads/useCase/2023/10/20/letter-writing7886.jpg', 'Create any type of letter you want to write e.g letter of approval e.t.c. or write a letter from scratch.', 'Write me a letter with this title \"[title]\" and the description: [description]', 9, 1, 'Type of letter e.g Letter of Appreciation e.t.c.', '', 'Description', 'Write here', 'Write short description here', 'Write description here', 3, 1, '2023-10-20 16:50:03', '2023-11-10 17:49:34'),
                (57, 'Memes Creation', 'assets/uploads/useCase/2023/10/26/memes-creation7709.jpg', 'Create funny and interesting memes with BetaAI system for your social media accounts e.t.c', 'Write me a meme with this title \"[title]\" and the description of the meme: [description]', 4, 1, 'Title of the meme', '', 'Description of the meme', 'Write here', 'Write short description here', 'Write description here', 2, 1, '2023-10-26 20:13:15', '2023-11-10 12:48:36'),
                (58, 'Physics', 'assets/uploads/useCase/2023/11/10/physics2074.png', 'Find topics, subtopics and Solve calculation on physics and get definitions and terms in Physics', 'Write me content with in physics \"[title]\" and the description : [description]', 9, 1, 'Topics of Physics e.g Fundamental Quantity e.t.c.', NULL, 'Description', 'Write here', 'Write short description here', 'Write description here', 1, 1, '2023-11-10 18:00:53', '2023-11-10 18:00:53');");
    }
}
