<?php

return [
    'name' => 'app_name',
    'type_logo' => 'uploads/site/own-site7189.png',
    'type_name' => 'Hat bazar',
    'type_footer' => 'HatBazar',
    'type_mail' => 'hatbazar@mail.com',
    'type_address' => 'Uttara vuter golie,',
    'footer_logo' => 'uploads/site/footer-logo4574.jpg',
    'favicon_icon' => 'uploads/site/f-icon1290.png',
    'type_fb' => 'facebook.com',
    'type_tw' => 'facebook.com',
    'type_google' => 'facebook.com',
    'type_insta' => 'instagram.com',
    'type_youtube' => 'youtube.com',
    'type_number' => '01685755707',
    'type_title' => 'Trasted Online shop',
    'type_register_title' => 'Start your 30-day free trial',
    'type_login_title' => 'Welcome back! Please enter your details',
    "meta_keys" => "XOXO CMS",
    "meta_desc" => 'XOXO  CMS',
    "meta_title" => 'XOXO  CMS',
    "meta_image" => "",
    'PAYPAL_ACTIVE' => 'on',
    'PAYPAL_CLIENT_ID' => 'AYYaAaNKLpw1_KI8bsPWMzHky2qwTo3qOv4yM4LfjMitAUuU22mbVIrgrgqvNqS_9OMMsMRo4gatQNN1',
    'PAYPAL_APP_SECRET' => 'AYYaAaNKLpw1_KI8bsPWMzHky2qwTo3qOv4yM4LfjMitAUuU22mbVIrgrgqvNqS_9OMMsMRo4gatQNN1',
    'STRIPE_ACTIVE' => 'on',
    'STRIPE_KEY' => 'pk_test_Nr6hlHbDo44RWI4N6QhdYZNP00KS5i1lKX',
    'STRIPE_SECRET' => 'sk_test_S5nEvoXdlANiZ82rWO99JEO800KB1boacQ',
    'RAZORPAY_ACTIVE' => 'on',
    'RAZORPAY_KEY' => 'rzp_test_qs2qz7KKUQbpgo',
    'RAZORPAY_SECRET' => 'PpcKi4Tlfx86Dtz2u9kDPxm1',
    'MOLLIE_ACTIVE' => 'on',
    'MOLLIE_KEY' => 'test_7WRmUeVGdRTG5G4Kk34rcaDgjxuUHj',
    'MOLLIE_Partner_ID' => '16905249',
    'MOLLIE_Profile_ID' => 'pfl_n3GFjcQ4EN',
    'tawk_to' => 'yes',
    'meta_key' => 'buwezalute@mailinator.com',
    'currency_sambol'=>'$',
];
